### ISSUE TITLE
2주차 작업

### ISSUE THREAD

**Issue by devhaeyeon** [dynamic-programmers/modern-js-deep-dive#7]
@qkreltms 

안녕하세요 ~

저장소에 권한이 없는 것 같아요 ~ 확인 부탁드릴게요 ~ !
<img width="726" alt="스크린샷 2021-05-23 오후 6 36 11" src="https://user-images.githubusercontent.com/5661544/119255281-ddf2f180-bbf5-11eb-9c1b-333cb096816c.png">

==

2주차 작업에 해당하는 링크는 아래와 같습니다.
https://www.notion.so/yundev/2nd-5-23-e0499386ef964421aa75549b98aac1d3

**Comment by qkreltms** [comment]
PR은 권한 상관없이 되는 것으로 알고있는데 main에서 작업하셨나요?? 아무튼 맴버 초대 보냈습니다 확인해주세요😃

**Comment by devhaeyeon** [comment]
해당 명령어가 떴을 때 실행한 명령어들을 기입하지 않았었네요 ~

```
git branch yundev-week2
git checkout yundev-week2
git commit -am "커밋메세지 작성"
git push origin yundev-week2
```

'저장소에 커밋 권한을 주고 싶은 동료가 있으면 “Collaborator” 로 추가해야 한다. Ben과 Jeff, Louise라는 동료가 있는데 그들이 내 저장소에 Push 할 수 있도록 하고 싶으면 내 프로젝트에 GitHub 계정들을 추가해야 한다. ' 라고 아래의 링크에서 나와 있네요 ~
https://git-scm.com/book/ko/v2/GitHub-GitHub-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

권한 부여 된 것 확인 되었구요 ~ 
다음 주 차부터 PR 올려서 요청 드리겠습니다 ~ :)

해당 스터디를 운영하시느라 고생 많으세여 ~ !)
